### ISSUE TITLE
Connect-Standalone ConfigDef error

### ISSUE THREAD

**Issue by vijayvepa** [justonedb/kafka-sink-pg-json#13]
Here are the connector.properties (credentials removed)

```properties
# Name of the connector (do not change)
#
name=justone-kafka-sink-pg-json
#
# Connector class (do not change)
#
connector.class=com.justone.kafka.sink.pg.json.PostgreSQLSinkConnector
#
# Number of tasks to be assigned to the connector (mandatory)
#
tasks.max=1
#
# Topics to consume from (mandatory)
#
topics=env.patientdb.Patients
#
# Server address/name hosting the database (optional - default is localhost)
#
db.host=*********
#
# Name of the database to connect to (mandatory)
#
db.database=*****
#
# Name of the user to connect to the database with (mandatory)
#
db.username=******
#
# Password to use for user authentication (optional - default is none)
#
db.password=******
#
# Schema of the table (mandatory)
#
db.schema=public
#
# Table to receive rows (mandatory)
#
db.table=patients
#
# Comma separated list of columns to receive json elements (mandatory)
#
db.columns=id,firstname,lastname,countrycode,dateofbirth,setupdate,organization,active
#
# Comma separated list of parse paths to retrieve json elements by (mandatory)
#
db.json.parse=/@_id,/@firstName,/@lastName,/@countryCode,/@dateOfBirth,/@setupDate,/@organizationId,/@active
#
# Type of delivery (mandatory). Must be one of fastest, guaranteed, synchronized
#
db.delivery=guaranteed
#
# Buffer size (bytes) used to cache writes
#
db.buffer.size=8000000
#

```

When starting the standalone confluent connect, 

```bash
connect-standalone justone-kafka-sink-pg-json-standalone.properties justone-kafka-sink-pg-json-connector.properties

```

we are seeing this error:
```bash
.....
[2017-10-13 19:46:25,376] INFO Starting REST server (org.apache.kafka.connect.runtime.rest.RestServer:98)
[2017-10-13 19:46:25,450] INFO jetty-9.2.15.v20160210 (org.eclipse.jetty.server.Server:327)
Oct 13, 2017 7:46:25 PM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: The (sub)resource method createConnector in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
WARNING: The (sub)resource method listConnectors in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
WARNING: The (sub)resource method listConnectorPlugins in org.apache.kafka.connect.runtime.rest.resources.ConnectorPluginsResource contains empty path annotation.
WARNING: The (sub)resource method serverInfo in org.apache.kafka.connect.runtime.rest.resources.RootResource contains empty path annotation.

[2017-10-13 19:46:25,886] INFO Started o.e.j.s.ServletContextHandler@662a09af{/,null,AVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:744)
[2017-10-13 19:46:25,898] INFO Started ServerConnector@132c65ab{HTTP/1.1}{0.0.0.0:8083} (org.eclipse.jetty.server.ServerConnector:266)
[2017-10-13 19:46:25,898] INFO Started @16556ms (org.eclipse.jetty.server.Server:379)
[2017-10-13 19:46:25,899] INFO REST server listening at http://10.57.91.191:8083/, advertising URL http://10.57.91.191:8083/ (org.apache.kafka.connect.runtime.rest.RestServer:150)
[2017-10-13 19:46:25,899] INFO Kafka Connect started (org.apache.kafka.connect.runtime.Connect:55)
[2017-10-13 19:46:25,902] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:100)
java.lang.AbstractMethodError: org.apache.kafka.connect.connector.Connector.config()Lorg/apache/kafka/common/config/ConfigDef;
	at org.apache.kafka.connect.connector.Connector.validate(Connector.java:132)
	at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:257)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:157)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:94)
[2017-10-13 19:46:25,903] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:65)
[2017-10-13 19:46:25,903] INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer:154)
[2017-10-13 19:46:25,913] INFO Stopped ServerConnector@132c65ab{HTTP/1.1}{0.0.0.0:8083} (org.eclipse.jetty.server.ServerConnector:306)
[2017-10-13 19:46:25,917] INFO Stopped o.e.j.s.ServletContextHandler@662a09af{/,null,UNAVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:865)
[2017-10-13 19:46:25,918] INFO REST server stopped (org.apache.kafka.connect.runtime.rest.RestServer:165)
[2017-10-13 19:46:25,919] INFO Herder stopping (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:76)
[2017-10-13 19:46:25,919] INFO Worker stopping (org.apache.kafka.connect.runtime.Worker:156)


```

**Comment by ivanursul** [comment]
Most probably, you are using a new version of Kafka/Confluent platform and kafka-sink-pg-json doesn't support it. Please compare:
[Connector.config](https://kafka.apache.org/0102/javadoc/org/apache/kafka/connect/connector/Connector.html#config()) and [PostgreSQLSinkConnector.java](https://github.com/justonedb/kafka-sink-pg-json/blob/master/src/main/java/com/justone/kafka/sink/pg/json/PostgreSQLSinkConnector.java)
shows that there's no config method implemented in **PostgreSQLSinkConnector**, so you have to fork this repo, implement it by yourself, or ask repo owner to do that.
