### ISSUE TITLE
java.lang.AbstractMethodError can't understand where to find a solution?

### ISSUE THREAD

**Issue by wolandec** [justonedb/kafka-sink-pg-json#15]
```
[2017-10-23 15:53:38,849] INFO Registered loader: sun.misc.Launcher$AppClassLoader@764c12b6 (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:199)
[2017-10-23 15:53:38,851] INFO Added plugin 'org.apache.kafka.connect.tools.VerifiableSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,851] INFO Added plugin 'org.apache.kafka.connect.file.FileStreamSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,851] INFO Added plugin 'org.apache.kafka.connect.tools.MockSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,852] INFO Added plugin 'org.apache.kafka.connect.tools.MockConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,852] INFO Added plugin 'org.apache.kafka.connect.tools.VerifiableSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,852] INFO Added plugin 'org.apache.kafka.connect.tools.MockSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,852] INFO Added plugin 'com.justone.kafka.sink.pg.json.PostgreSQLSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,852] INFO Added plugin 'org.apache.kafka.connect.file.FileStreamSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,852] INFO Added plugin 'org.apache.kafka.connect.tools.SchemaSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,852] INFO Added plugin 'org.apache.kafka.connect.converters.ByteArrayConverter' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,852] INFO Added plugin 'org.apache.kafka.connect.storage.StringConverter' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,852] INFO Added plugin 'org.apache.kafka.connect.json.JsonConverter' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,852] INFO Added plugin 'org.apache.kafka.connect.transforms.InsertField$Value' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,853] INFO Added plugin 'org.apache.kafka.connect.transforms.ExtractField$Value' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,853] INFO Added plugin 'org.apache.kafka.connect.transforms.TimestampRouter' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,853] INFO Added plugin 'org.apache.kafka.connect.transforms.Flatten$Value' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,854] INFO Added plugin 'org.apache.kafka.connect.transforms.SetSchemaMetadata$Value' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,854] INFO Added plugin 'org.apache.kafka.connect.transforms.ValueToKey' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,854] INFO Added plugin 'org.apache.kafka.connect.transforms.RegexRouter' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,854] INFO Added plugin 'org.apache.kafka.connect.transforms.Cast$Key' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,854] INFO Added plugin 'org.apache.kafka.connect.transforms.ReplaceField$Value' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,854] INFO Added plugin 'org.apache.kafka.connect.transforms.MaskField$Key' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,854] INFO Added plugin 'org.apache.kafka.connect.transforms.TimestampConverter$Key' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,854] INFO Added plugin 'org.apache.kafka.connect.transforms.InsertField$Key' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,854] INFO Added plugin 'org.apache.kafka.connect.transforms.SetSchemaMetadata$Key' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,854] INFO Added plugin 'org.apache.kafka.connect.transforms.Flatten$Key' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,854] INFO Added plugin 'org.apache.kafka.connect.transforms.HoistField$Value' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,854] INFO Added plugin 'org.apache.kafka.connect.transforms.MaskField$Value' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,855] INFO Added plugin 'org.apache.kafka.connect.transforms.ExtractField$Key' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,855] INFO Added plugin 'org.apache.kafka.connect.transforms.Cast$Value' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,855] INFO Added plugin 'org.apache.kafka.connect.transforms.HoistField$Key' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,855] INFO Added plugin 'org.apache.kafka.connect.transforms.TimestampConverter$Value' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,855] INFO Added plugin 'org.apache.kafka.connect.transforms.ReplaceField$Key' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:132)
[2017-10-23 15:53:38,855] INFO Added aliases 'PostgreSQLSinkConnector' and 'PostgreSQLSink' to plugin 'com.justone.kafka.sink.pg.json.PostgreSQLSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:293)
[2017-10-23 15:53:38,856] INFO Added aliases 'FileStreamSinkConnector' and 'FileStreamSink' to plugin 'org.apache.kafka.connect.file.FileStreamSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:293)
[2017-10-23 15:53:38,856] INFO Added aliases 'FileStreamSourceConnector' and 'FileStreamSource' to plugin 'org.apache.kafka.connect.file.FileStreamSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:293)
[2017-10-23 15:53:38,856] INFO Added aliases 'MockConnector' and 'Mock' to plugin 'org.apache.kafka.connect.tools.MockConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:293)
[2017-10-23 15:53:38,856] INFO Added aliases 'MockSinkConnector' and 'MockSink' to plugin 'org.apache.kafka.connect.tools.MockSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:293)
[2017-10-23 15:53:38,856] INFO Added aliases 'MockSourceConnector' and 'MockSource' to plugin 'org.apache.kafka.connect.tools.MockSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:293)
[2017-10-23 15:53:38,856] INFO Added aliases 'SchemaSourceConnector' and 'SchemaSource' to plugin 'org.apache.kafka.connect.tools.SchemaSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:293)
[2017-10-23 15:53:38,856] INFO Added aliases 'VerifiableSinkConnector' and 'VerifiableSink' to plugin 'org.apache.kafka.connect.tools.VerifiableSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:293)
[2017-10-23 15:53:38,856] INFO Added aliases 'VerifiableSourceConnector' and 'VerifiableSource' to plugin 'org.apache.kafka.connect.tools.VerifiableSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:293)
[2017-10-23 15:53:38,856] INFO Added aliases 'ByteArrayConverter' and 'ByteArray' to plugin 'org.apache.kafka.connect.converters.ByteArrayConverter' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:293)
[2017-10-23 15:53:38,857] INFO Added aliases 'JsonConverter' and 'Json' to plugin 'org.apache.kafka.connect.json.JsonConverter' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:293)
[2017-10-23 15:53:38,857] INFO Added aliases 'StringConverter' and 'String' to plugin 'org.apache.kafka.connect.storage.StringConverter' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:293)
[2017-10-23 15:53:38,858] INFO Added alias 'RegexRouter' to plugin 'org.apache.kafka.connect.transforms.RegexRouter' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:290)
[2017-10-23 15:53:38,858] INFO Added alias 'TimestampRouter' to plugin 'org.apache.kafka.connect.transforms.TimestampRouter' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:290)
[2017-10-23 15:53:38,858] INFO Added alias 'ValueToKey' to plugin 'org.apache.kafka.connect.transforms.ValueToKey' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:290)
[2017-10-23 15:53:38,868] INFO StandaloneConfig values: 
        access.control.allow.methods = 
        access.control.allow.origin = 
        bootstrap.servers = [localhost:9092]
        internal.key.converter = class org.apache.kafka.connect.json.JsonConverter
        internal.value.converter = class org.apache.kafka.connect.json.JsonConverter
        key.converter = class org.apache.kafka.connect.storage.StringConverter
        offset.flush.interval.ms = 60000
        offset.flush.timeout.ms = 5000
        offset.storage.file.filename = /tmp/connect.offsets
        plugin.path = null
        rest.advertised.host.name = null
        rest.advertised.port = null
        rest.host.name = null
        rest.port = 8083
        task.shutdown.graceful.timeout.ms = 5000
        value.converter = class org.apache.kafka.connect.storage.StringConverter
 (org.apache.kafka.connect.runtime.standalone.StandaloneConfig:223)
[2017-10-23 15:53:38,951] INFO Logging initialized @3118ms (org.eclipse.jetty.util.log:186)
[2017-10-23 15:53:39,065] INFO Kafka Connect starting (org.apache.kafka.connect.runtime.Connect:49)
[2017-10-23 15:53:39,065] INFO Herder starting (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:70)
[2017-10-23 15:53:39,065] INFO Worker starting (org.apache.kafka.connect.runtime.Worker:144)
[2017-10-23 15:53:39,066] INFO Starting FileOffsetBackingStore with file /tmp/connect.offsets (org.apache.kafka.connect.storage.FileOffsetBackingStore:59)
[2017-10-23 15:53:39,067] INFO Worker started (org.apache.kafka.connect.runtime.Worker:149)
[2017-10-23 15:53:39,068] INFO Herder started (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:72)
[2017-10-23 15:53:39,068] INFO Starting REST server (org.apache.kafka.connect.runtime.rest.RestServer:98)
[2017-10-23 15:53:39,121] INFO jetty-9.2.15.v20160210 (org.eclipse.jetty.server.Server:327)
окт 23, 2017 3:53:39 PM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: The (sub)resource method listConnectors in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
WARNING: The (sub)resource method createConnector in org.apache.kafka.connect.runtime.rest.resources.ConnectorsResource contains empty path annotation.
WARNING: The (sub)resource method listConnectorPlugins in org.apache.kafka.connect.runtime.rest.resources.ConnectorPluginsResource contains empty path annotation.
WARNING: The (sub)resource method serverInfo in org.apache.kafka.connect.runtime.rest.resources.RootResource contains empty path annotation.

[2017-10-23 15:53:39,443] INFO Started o.e.j.s.ServletContextHandler@5d8ae8da{/,null,AVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:744)
[2017-10-23 15:53:39,451] INFO Started ServerConnector@4e692717{HTTP/1.1}{0.0.0.0:8083} (org.eclipse.jetty.server.ServerConnector:266)
[2017-10-23 15:53:39,451] INFO Started @3619ms (org.eclipse.jetty.server.Server:379)
[2017-10-23 15:53:39,452] INFO REST server listening at http://127.0.0.1:8083/, advertising URL http://127.0.0.1:8083/ (org.apache.kafka.connect.runtime.rest.RestServer:150)
[2017-10-23 15:53:39,452] INFO Kafka Connect started (org.apache.kafka.connect.runtime.Connect:55)
[2017-10-23 15:53:39,454] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:100)
java.lang.AbstractMethodError: org.apache.kafka.connect.connector.Connector.config()Lorg/apache/kafka/common/config/ConfigDef;
        at org.apache.kafka.connect.connector.Connector.validate(Connector.java:132)
        at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:257)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:157)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:94)
[2017-10-23 15:53:39,455] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:65)
[2017-10-23 15:53:39,456] INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer:154)
[2017-10-23 15:53:39,457] INFO Stopped ServerConnector@4e692717{HTTP/1.1}{0.0.0.0:8083} (org.eclipse.jetty.server.ServerConnector:306)
[2017-10-23 15:53:39,461] INFO Stopped o.e.j.s.ServletContextHandler@5d8ae8da{/,null,UNAVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:865)
[2017-10-23 15:53:39,462] INFO REST server stopped (org.apache.kafka.connect.runtime.rest.RestServer:165)
[2017-10-23 15:53:39,462] INFO Herder stopping (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:76)
[2017-10-23 15:53:39,462] INFO Worker stopping (org.apache.kafka.connect.runtime.Worker:156)
[2017-10-23 15:53:39,462] INFO Stopped FileOffsetBackingStore (org.apache.kafka.connect.storage.FileOffsetBackingStore:67)
[2017-10-23 15:53:39,462] INFO Worker stopped (org.apache.kafka.connect.runtime.Worker:176)
[2017-10-23 15:53:39,462] INFO Herder stopped (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:86)
[2017-10-23 15:53:39,462] INFO Kafka Connect stopped (org.apache.kafka.connect.runtime.Connect:70)

```

**Comment by yuexiongHNU** [comment]
I get the same error, have you resolved it?

**Comment by wolandec** [comment]
@yuexiongHNU No, I've downloaded confluent and test it. The connector works fine there.

**Comment by yuexiongHNU** [comment]
Thank you， I've choose another way to implement writing data from kafka to postgres

**Comment by agouz** [comment]
hey there,
I faced the same error, my problem was my Kakfa version is newer,  you have to implement the config operation.

Try to clone the project and compile it with your kafka version and see if it compiles.

the problem was solved by adding the following to "PostgreSQLSinkConnector"

````
private static final ConfigDef CONFIG_DEF = new ConfigDef();

  @Override
  public ConfigDef config() {
    return CONFIG_DEF;
  }

  @Override
  public Config validate(Map<String, String> connectorConfigs) {
      ConfigDef configDef = config();
      List<ConfigValue> configValues = configDef.validate(connectorConfigs);
      return new Config(configValues);
  }
````

you need the following imports too
`
```
import org.apache.kafka.common.config.Config;
import org.apache.kafka.common.config.ConfigDef;
import org.apache.kafka.common.config.ConfigValue;
```
`

**Comment by junaidrazzaq323** [comment]
@agouz I have cloned the project and tried to compile it but I get maven dependency errors in pom.xml on artifact id `justone-json` and `justone-pgwriter`. @yuexiongHNU What other way have you tried to write from kafka to postgres?

**Comment by yuexiongHNU** [comment]
@junaidrazzaq323  I used the plugin that we developed, not very common for most usage. Maybe I will improve it later

**Comment by junaidrazzaq323** [comment]
@yuexiongHNU Can you share the plugin that you developed?

**Comment by junaidrazzaq323** [comment]
@wolandec How have you tried the connector with confluent? Can you kindly share the details?

**Comment by yuexiongHNU** [comment]
@junaidrazzaq323  Maybe later, It's not so common now

**Comment by wolandec** [comment]
@junaidrazzaq323 That was fairly simple. I just download a free version of Confluent and start it. There is a good documentation and with some tuning it starts work fine. There is one big problem,free version have no cluster feature.

**Comment by junaidrazzaq323** [comment]
@wolandec I have tried the confluent JDBC sink connector. I have followed [this post](https://docs.confluent.io/current/connect/connect-jdbc/docs/sink_connector.html), changing sink from SQLite to PostgreSql. When I produce a record into a topic I get the following error:

```
[2018-03-13 11:37:37,360] INFO Initializing writer using SQL dialect: PostgreSqlDialect (io.confluent.connect.jdbc.sink.JdbcSinkTask:52)
[2018-03-13 11:37:37,361] INFO WorkerSinkTask{id=test-sink-0} Sink task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:268)
[2018-03-13 11:37:37,606] WARN [Consumer clientId=consumer-1, groupId=connect-test-sink] Error while fetching metadata with correlation id 2 : {orders=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient:246)
[2018-03-13 11:37:37,617] INFO [Consumer clientId=consumer-1, groupId=connect-test-sink] Discovered coordinator jojo:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:341)
[2018-03-13 11:37:37,625] INFO [Consumer clientId=consumer-1, groupId=connect-test-sink] Revoking previously assigned partitions [] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:341)
[2018-03-13 11:37:37,630] INFO [Consumer clientId=consumer-1, groupId=connect-test-sink] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:336)
[2018-03-13 11:37:37,723] WARN [Consumer clientId=consumer-1, groupId=connect-test-sink] Error while fetching metadata with correlation id 6 : {orders=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient:246)
[2018-03-13 11:37:37,724] WARN [Consumer clientId=consumer-1, groupId=connect-test-sink] The following subscribed topics are not assigned to any members: [orders]  (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:241)
[2018-03-13 11:37:37,778] INFO [Consumer clientId=consumer-1, groupId=connect-test-sink] Successfully joined group with generation 1 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:341)
[2018-03-13 11:37:37,826] INFO [Consumer clientId=consumer-1, groupId=connect-test-sink] Setting newly assigned partitions [] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:341)
[2018-03-13 11:37:37,826] INFO [Consumer clientId=consumer-1, groupId=connect-test-sink] Revoking previously assigned partitions [] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:341)
[2018-03-13 11:37:37,826] INFO [Consumer clientId=consumer-1, groupId=connect-test-sink] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:336)
[2018-03-13 11:37:37,833] INFO [Consumer clientId=consumer-1, groupId=connect-test-sink] Successfully joined group with generation 2 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:341)
[2018-03-13 11:37:37,833] INFO [Consumer clientId=consumer-1, groupId=connect-test-sink] Setting newly assigned partitions [orders-0] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:341)
[2018-03-13 11:42:00,448] ERROR WorkerSinkTask{id=test-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:515)
java.lang.NoClassDefFoundError: Could not initialize class org.apache.calcite.jdbc.Driver
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.sql.DriverManager.isDriverAllowed(DriverManager.java:556)
	at java.sql.DriverManager.getConnection(DriverManager.java:661)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:85)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getValidConnection(CachedConnectionProvider.java:68)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:56)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:69)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2018-03-13 11:42:00,450] ERROR WorkerSinkTask{id=test-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:172)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:517)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.calcite.jdbc.Driver
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.sql.DriverManager.isDriverAllowed(DriverManager.java:556)
	at java.sql.DriverManager.getConnection(DriverManager.java:661)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:85)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getValidConnection(CachedConnectionProvider.java:68)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:56)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:69)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
	... 10 more
[2018-03-13 11:42:00,451] ERROR WorkerSinkTask{id=test-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:173)
[2018-03-13 11:42:00,451] INFO Stopping task (io.confluent.connect.jdbc.sink.JdbcSinkTask:96)

```

Do you know about this or how can I resolve this?

Thank you.

**Comment by wolandec** [comment]
I think confluent cant find driver class.

**Comment by junaidrazzaq323** [comment]
But I have exported `postgresql-jdbc.jar` in the `CLASSPATH`. What else can I try?
