### ISSUE TITLE
AbstractMethodError when running in Distributed Mode

### ISSUE THREAD

**Issue by chen7515** [justonedb/kafka-sink-pg-json#17]
I am trying to start a JustOne connector with the following REST request (formatted for easier reading):
curl -X POST -H "Content-Type: application/json" --data '{
"name": "JustOnePostgreSink",
"config": { 
"connector.class": "com.justone.kafka.sink.pg.json.PostgreSQLSinkConnector",
"tasks.max": "1",
"topics": "org.mitre.caasd.sunbird.datatransport.AudioSegmentMetaData.10.0.0.analysis-decode",
"db.host": "localhost",
"db.database": "sunbird_db",
"db.username": "****",
"db.schema": "****",
"db.table": "JustOne_AudioSegmentMetaData",
"db.columns": "segmentMetadataId,dataSet,partition,offset,audioOrigin,audioChannel,facilityCode,controllerPosition,audioEncoding,speakerClassLabel,segmentStartTime,segmentEndTime,timestamp,best_hypothesis_transcription,best_hypothesis_confidence,semanticConcepts",
"db.json.parse": "/@segmentMetadataId,/@dataSet,/@partition,/@offset,/@audioOrigin,/@audioChannel,/@facilityCode,/@controllerPosition,/@audioEncoding,/@speakerClassLabel,/@segmentStartTime,/@segmentEndTime,/@timestamp,/@decodeHypotheses/#0/@transcription,/@decodeHypotheses/#0/@confidence,/@decodeHypotheses/#0/@semanticConceptList",
"db.delivery": "synchronized",
"db.buffer.size": "800000",
"key.converter": "org.apache.kafka.connect.storage.StringConverter",
"value.converter": "org.apache.kafka.connect.storage.StringConverter",
"key.converter.schemas.enable": "false",
"value.converter.schemas.enable": "false" 
}}' http://localhost:8083/connectors

I am getting an AbstractMethodError. This appears similar to a previous issue that is still open. Full stacktrace below:
[2018-04-18 10:12:46,115] WARN /connectors (org.eclipse.jetty.server.HttpChannel:396)
javax.servlet.ServletException: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.AbstractMethodError
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:130)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.AbstractMethodError
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        ... 10 more
Caused by: org.glassfish.jersey.server.ContainerException: java.lang.AbstractMethodError
        at org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:278)
        at org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:260)
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:509)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:334)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        ... 23 more
Caused by: java.lang.AbstractMethodError
        at org.apache.kafka.connect.connector.Connector.validate(Connector.java:132)
        at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:257)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:509)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:506)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:249)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:199)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
[2018-04-18 10:12:46,115] WARN Could not send response error 500: javax.servlet.ServletException: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.AbstractMethodError (org.eclipse.jetty.server.HttpChannel:482)

**Comment by lordgraysith** [comment]
@chen7515 I'm having the same problem here. Have you had any luck? Does anyone look at these issues?

**Comment by lordgraysith** [comment]
Quick update: looks like this library is coded against old contracts. See the `Connector.java` from 2015 
https://github.com/apache/kafka/blob/f2031d40639ef34c1591c22971394ef41c87652c/connect/api/src/main/java/org/apache/kafka/connect/connector/Connector.java

And the one from 2016:
https://github.com/apache/kafka/blob/c07d017227f319250e5c373f8a6f504874ecfbf2/connect/api/src/main/java/org/apache/kafka/connect/connector/Connector.java

The real question: what else breaks if we fix that??
