### ISSUE TITLE
Confluent 3.0

### ISSUE THREAD

**Issue by decoursin** [justonedb/kafka-sink-pg-json#7]
I tried getting the connector to work, but I wasn't able to. Could it be because I have confluent 3.0 and not confluent 2.0?

Here's the output from the console after running `connect-standalone justone-kafka-sink-pg-json-standalone.properties justone-kafka-sink-pg-json-connector.properties`.
```
[2017-01-21 23:40:33,711] INFO Started o.e.j.s.ServletContextHandler@4b672daa{/,null,AVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:744)
[2017-01-21 23:40:33,791] INFO Started ServerConnector@1e50303f{HTTP/1.1}{0.0.0.0:8083} (org.eclipse.jetty.server.ServerConnector:266)
[2017-01-21 23:40:33,791] INFO Started @3438ms (org.eclipse.jetty.server.Server:379)
[2017-01-21 23:40:33,792] INFO REST server listening at http://127.0.1.1:8083/, advertising URL http://127.0.1.1:8083/ (org.apache.kafka.connect.runtime.rest.RestServer:150)
[2017-01-21 23:40:33,792] INFO Kafka Connect started (org.apache.kafka.connect.runtime.Connect:58)
[2017-01-21 23:40:33,809] ERROR Failed to start connector justone-kafka-sink-pg-json (org.apache.kafka.connect.runtime.Worker:166)
java.lang.NoSuchMethodError: org.apache.kafka.common.config.ConfigDef.define(Ljava/lang/String;Lorg/apache/kafka/common/config/ConfigDef$Type;Lorg/apache/kafka/common/config/ConfigDef$Importance;Ljava/lang/String;Ljava/lang/String;ILorg/apache/kafka/common/config/ConfigDef$Width;Ljava/lang/String;)Lorg/apache/kafka/common/config/ConfigDef;
	at org.apache.kafka.connect.runtime.ConnectorConfig.configDef(ConnectorConfig.java:72)
	at org.apache.kafka.connect.runtime.ConnectorConfig.<init>(ConnectorConfig.java:85)
	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:157)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.startConnector(StandaloneHerder.java:237)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:159)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:96)
[2017-01-21 23:40:33,838] ERROR Failed to create job for justone-kafka-sink-pg-json-connector.properties (org.apache.kafka.connect.cli.ConnectStandalone:91)
[2017-01-21 23:40:33,838] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:102)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.errors.ConnectException: Failed to start connector: justone-kafka-sink-pg-json
	at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:80)
	at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:67)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:99)
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to start connector: justone-kafka-sink-pg-json
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:160)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:96)
[2017-01-21 23:40:33,838] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:68)
```

**Comment by decoursin** [comment]
Closing...

I eventually got it to work, I don't know what the problem was.
